baseURL = ""
languageCode = "en-us"
title = "Matthew Gergus"
theme = "hello-friend-ng"


[params]
  customCSS = ["css/theme-vars-override.css"]

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/matthewgergus/"

  [[params.social]]
    name = "github"
    url = "https://github.com/HeckinMatt"

[params.footer]
  trademark = false
  rss = false
  author = false
  copyright = "Â© {{ now.Year }} Matthew Gergus"
  topText = []

   



 
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 20

[[menu.main]]
identifier = "competitions"
name = "Competitions"
url = "/competitions/"
weight = 30

[[menu.main]]
identifier = "certifications"
name = "Certifications"
url = "/certifications/"
weight = 30



